Err with nnModel model passed to view(+)
InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'ClaveSol.Models.nnModels', but this ViewDataDictionary instance requires a model item of type 'System.Collections.Generic.IEnumerable`1[ClaveSol.Models.nnModels]'.